# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "0e36454be772919b5d1841638e28ffcc"
name = "adaptive-negotiation-app"
handle = "adaptive-negotiation-app-9"
application_url = "https://aye-xuaq.onrender.com"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = ["products/update"]
  uri = "pubsub://pubsub-461523:topical-sub"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [	"https://aye-xuaq.onrender.com/auth/callback",
    			"https://aye-xuaq.onrender.com/auth/shopify/callback",
    			"https://aye-xuaq.onrender.com/api/auth/callback" ]

[pos]
embedded = false
